# Generated by Django 5.2 on 2025-05-11 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_limit",
            field=models.CharField(
                blank=True,
                choices=[("All", "All"), ("Kids", "Kids")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_limit",
            field=models.CharField(
                blank=True,
                choices=[("All", "All"), ("Kids", "Kids")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
